CREATE DATABASE COMPUTERSHOP;
####
CREATE TABLE CUSTOMER(
CID VARCHAR(10) NOT NULL,
NAME VARCHAR(40) NOT NULL,
NIC VARCHAR(10)NOT NULL,
ADDRESS VARCHAR(40)NOT NULL,
CONTACT INT(10)NOT NULL,
CONSTRAINT PRIMARY KEY (CID)
)

ENGINE=InnoDB DEFAULT CHARSET=utf8;####CREATE TABLE ITEM(CODE VARCHAR (10)NOT NULL,NAME VARCHAR(40)NOT NULL,DESCRIPTION VARCHAR(50)NOT NULL,ITEMTYPE VARCHAR(50)NOT NULL,PRICE DECIMAL(10.0)NOT NULL,QTY INT(10)NOT NULL,CONSTRAINT PRIMARY KEY (CODE))ENGINE=InnoDB DEFAULT CHARSET=utf8;####CREATE TABLE ORDERS(OID VARCHAR(10)NOT NULL,CID VARCHAR(10)NOT NULL,ORDERDATE DATE NOT NULL,AMOUNT DECIMAL(10.0)NOT NULL,CONSTRAINT PRIMARY KEY (OID),CONSTRAINT FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)ON UPDATE CASCADE ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8;####CREATE TABLE ORDERDETAIL(OID VARCHAR(10)NOT NULL,CODE VARCHAR(10) NOT NULL,ORDERQTY INT(10)NOT NULL,PRICE DECIMAL(10.0)NOT NULL,CONSTRAINT PRIMARY KEY (OID,CODE),CONSTRAINT FOREIGN KEY (OID) REFERENCES ORDERS(OID)ON UPDATE CASCADE ON DELETE CASCADE,CONSTRAINT FOREIGN KEY (CODE) REFERENCES ITEM(CODE)ON UPDATE CASCADE ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8;####CREATE TABLE ACCOUNT(USERNAME VARCHAR(10)NOT NULL,USERPASSWORD VARCHAR(10)NOT NULL,CONSTRAINT PRIMARY KEY (USERNAME))ENGINE=InnoDB DEFAULT CHARSET=utf8;






	
	
	




	
	




	
	
	
	
	
	
	
	
	
	


	
	
